### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by niku419** [Shruthi-Sivagnanam/emailHunt#2]
How will it work without providing a password

**Comment by Shruthi-Sivagnanam** [comment]
Thanks for your concern. It surprises me that my GitHub account have came to your notice.

This is actually built with help elastic mail api. SMTP server was created in a elastic mail. The mail is send through this created server. This don't need sender's password.

https://elasticemail.com/email-api

Actually the mail send from your mail id will not be present in your sent attempts.

**Comment by niku419** [comment]
Okay I understand that it won't be present in my mail sent tab. But I
haven't received the mails either

**Comment by Shruthi-Sivagnanam** [comment]
![Screenshot (219)](https://github.com/Shruthi-Sivagnanam/emailHunt/assets/82823305/b9397d55-2775-4c98-a232-eb5cf55b641c)


This is the dashboard of the smtp server. The mails are getting bounced and the reason is stated that it is due to software issues. I will see to it and update to you soon.

**Comment by niku419** [comment]
Ok, thanks for the update.
If you fix it please let me know...anyways the UI and showing valid emails
part was very impressive. Keep up the good work
